/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminCredentials = IDL.Record({
  'userId' : IDL.Text,
  'password' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mobile = IDL.Text;
export const Credentials = IDL.Record({
  'password' : IDL.Text,
  'mobile' : Mobile,
});
export const ServiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'processing' : IDL.Null,
});
export const TimestampNanos = IDL.Int;
export const ServiceRequest = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : ServiceStatus,
  'serviceName' : IDL.Text,
  'serviceHindiName' : IDL.Text,
  'documents' : IDL.Vec(IDL.Text),
  'submittedAt' : TimestampNanos,
  'aadhaar' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'mobile' : Mobile });
export const Password = IDL.Text;
export const Registration = IDL.Record({
  'password' : Password,
  'mobile' : Mobile,
});
export const NewServiceRequest = IDL.Record({
  'dob' : IDL.Text,
  'customerName' : IDL.Text,
  'serviceName' : IDL.Text,
  'serviceHindiName' : IDL.Text,
  'documents' : IDL.Vec(IDL.Text),
  'aadhaar' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'pincode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([AdminCredentials], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCredentials' : IDL.Func([], [IDL.Vec(Credentials)], ['query']),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyServiceRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([Credentials], [IDL.Bool], []),
  'register' : IDL.Func([Registration], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitServiceRequest' : IDL.Func([NewServiceRequest], [IDL.Text], []),
  'updateRequestStatus' : IDL.Func([IDL.Text, ServiceStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminCredentials = IDL.Record({
    'userId' : IDL.Text,
    'password' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mobile = IDL.Text;
  const Credentials = IDL.Record({ 'password' : IDL.Text, 'mobile' : Mobile });
  const ServiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'processing' : IDL.Null,
  });
  const TimestampNanos = IDL.Int;
  const ServiceRequest = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : ServiceStatus,
    'serviceName' : IDL.Text,
    'serviceHindiName' : IDL.Text,
    'documents' : IDL.Vec(IDL.Text),
    'submittedAt' : TimestampNanos,
    'aadhaar' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'mobile' : Mobile });
  const Password = IDL.Text;
  const Registration = IDL.Record({ 'password' : Password, 'mobile' : Mobile });
  const NewServiceRequest = IDL.Record({
    'dob' : IDL.Text,
    'customerName' : IDL.Text,
    'serviceName' : IDL.Text,
    'serviceHindiName' : IDL.Text,
    'documents' : IDL.Vec(IDL.Text),
    'aadhaar' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'pincode' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([AdminCredentials], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCredentials' : IDL.Func([], [IDL.Vec(Credentials)], ['query']),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyServiceRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([Credentials], [IDL.Bool], []),
    'register' : IDL.Func([Registration], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitServiceRequest' : IDL.Func([NewServiceRequest], [IDL.Text], []),
    'updateRequestStatus' : IDL.Func([IDL.Text, ServiceStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };