/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminCredentials { 'userId' : string, 'password' : string }
export interface Credentials { 'password' : string, 'mobile' : Mobile }
export type Mobile = string;
export interface NewServiceRequest {
  'dob' : string,
  'customerName' : string,
  'serviceName' : string,
  'serviceHindiName' : string,
  'documents' : Array<string>,
  'aadhaar' : string,
  'district' : string,
  'state' : string,
  'fatherName' : string,
  'address' : string,
  'mobile' : string,
  'pincode' : string,
}
export type Password = string;
export interface Registration { 'password' : Password, 'mobile' : Mobile }
export interface ServiceRequest {
  'id' : string,
  'dob' : string,
  'customerName' : string,
  'status' : ServiceStatus,
  'serviceName' : string,
  'serviceHindiName' : string,
  'documents' : Array<string>,
  'submittedAt' : TimestampNanos,
  'aadhaar' : string,
  'district' : string,
  'state' : string,
  'fatherName' : string,
  'address' : string,
  'mobile' : string,
  'pincode' : string,
}
export type ServiceStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'processing' : null };
export type TimestampNanos = bigint;
export interface UserProfile { 'mobile' : Mobile }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[AdminCredentials], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCredentials' : ActorMethod<[], Array<Credentials>>,
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyServiceRequests' : ActorMethod<[string], Array<ServiceRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[Credentials], boolean>,
  'register' : ActorMethod<[Registration], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitServiceRequest' : ActorMethod<[NewServiceRequest], string>,
  'updateRequestStatus' : ActorMethod<[string, ServiceStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];